name: kayou
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.6
  # firebase_storage: ^8.0.5
  # firebase_storage: ^10.0.5
  firebase_storage: ^10.2.4
  # firebase_auth: ^1.1.2
  # firebase_auth: ^3.1.3
  firebase_auth: ^3.3.4
  # cloud_firestore: ^1.0.7
  # cloud_firestore: ^2.5.3
  cloud_firestore: ^3.1.5
  google_sign_in: ^5.1.1
  sign_in_with_apple: ^4.1.0
  introduction_screen: ^3.0.2
  persistent_bottom_nav_bar_v2: ^4.2.4
  chips_choice_null_safety: ^2.0.6
  url_launcher: ^6.0.12
  loading_animations: ^2.1.0
  cached_network_image: ^3.2.1
  # flutter_login_facebook: ^1.1.0
  mailer: ^5.1.1
  pinput: ^2.0.0
  package_info: ^2.0.2
  shared_preferences: ^2.0.5
  pedometer: ^3.0.0
  # activity_recognition_flutter: ^3.0.1
  permission_handler: ^10.0.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.1.0
  connectivity_plus: ^2.0.2
  purchases_flutter: ^3.10.0
  flutter_foreground_task: ^3.8.1
  carousel_slider: ^4.0.0
  google_maps_flutter: ^2.0.11
  animated_bottom_navigation_bar: ^1.0.1
  qr_flutter: ^4.0.0
  rflutter_alert: ^2.0.2
  flutter_share: ^2.0.0

  flutter_html: ^3.0.0-alpha.5
  grouped_list: ^5.1.2
  google_fonts: ^3.0.1
  geolocator: ^9.0.1
  flutter_map_location_marker: ^4.1.3
  screenshot: ^1.2.3
  path_provider: ^2.0.5
  external_path: ^1.0.1
  confirm_dialog: ^1.0.0
  pull_to_refresh: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  health: ^4.1.1
  app_settings: ^4.1.1
  # device_info: ^2.0.3
  flutter_countdown_timer: ^4.1.0
  video_player: ^2.2.10
  flutter_calendar_carousel: ^2.1.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.1.5
  youtube_player_flutter: ^8.0.0
  tutorial_coach_mark: ^1.2.3
  sqflite: ^2.0.1
  map_launcher: ^2.2.3
  flutter_feather_icons: ^2.0.0+1
  flutter_native_splash: ^2.2.7
  barcode_widget: ^2.0.0
  device_apps: ^2.2.0
  fluttericon: ^2.0.0
  material_design_icons_flutter: ^5.0.6595
  syncfusion_flutter_gauges: ^20.2.40
  syncfusion_flutter_charts: ^20.2.40
  syncfusion_flutter_barcodes: ^20.2.40
  flutter_easyloading: ^3.0.5
  flutter_cache_manager: ^3.3.0
  platform: ^3.1.0
  flutter_math_fork: ^0.6.2
  # background_fetch: ^1.1.0
  workmanager: ^0.5.0
  device_info_plus: ^4.1.2
  firebase_analytics: ^9.3.3
  flutter_background_service: ^2.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter 
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/images/Cagou.png
    - assets/images/normalPin.png
    - assets/images/selectedPin.png
    - assets/images/logo_google.png
    - assets/images/logo_apple.png
    - assets/images/logo_insta_2.png
    - assets/images/logo_messenger_1.png
    - assets/images/logo-fit.png
    - assets/images/logo_language.png
    - assets/images/logo_doc.png
    - assets/images/activite.gif
    - assets/images/intro/Slide1.jpg
    - assets/images/intro/Slide2.jpg
    - assets/images/intro/Slide3.jpg
    - assets/images/logo192.png
    - assets/images/logo_ads.jpg
    - assets/images/logo_ads.png
    - assets/images/logo_map.png
    - assets/images/logo_sms.png
    - assets/images/logo_kayou.png
    - assets/images/logo_cashback.png
    - assets/images/foot_icon.png
    - assets/images/medal_icon.png
    - assets/images/moneybox_icon.png
    - assets/images/tuto_icon.png
    - assets/images/pas.png
    - assets/images/shop.png
    - assets/images/trophy.png
    - assets/images/parrain.png
    - assets/images/trophymenu.png
  # TUTO 
    - assets/images/tuto/Partenaires-01.jpg
    - assets/images/tuto/Partenaires-02.jpg
    - assets/images/tuto/Plan-01.jpg
    - assets/images/tuto/Plan-02.jpg
    - assets/images/tuto/Recompenses-01.jpg
    - assets/images/tuto/Recompenses-02.jpg
    - assets/images/tuto/activity-01.jpg
    - assets/images/tuto/activity-02.jpg
    - assets/images/tuto/activity-03.jpg
    - assets/images/tuto/activity-04.jpg
    - assets/images/tuto/activity-05.jpg
    - assets/images/tuto/activity-06.jpg
    - assets/images/tuto/activity-07.jpg
    - assets/images/tuto/activity-08.jpg
    - assets/images/tuto/activity-09.jpg
    - assets/images/tuto/activity-10.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
