// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXUvER8R-eRBUSM3rgWemprvtzrxhCMOs',
    appId: '1:58788357910:web:e876741282ac4d46a3d237',
    messagingSenderId: '58788357910',
    projectId: 'kayou-47924',
    authDomain: 'kayou-47924.firebaseapp.com',
    storageBucket: 'kayou-47924.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkCK9h1y4pm9Hr8iKVjLNJTBzFbedw7Q',
    appId: '1:58788357910:android:28985ffa03d799c5a3d237',
    messagingSenderId: '58788357910',
    projectId: 'kayou-47924',
    storageBucket: 'kayou-47924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKx94sJHtx6yL3zoy8F2pBtylzwlTMRaw',
    appId: '1:58788357910:ios:3e7add3fbcab628fa3d237',
    messagingSenderId: '58788357910',
    projectId: 'kayou-47924',
    storageBucket: 'kayou-47924.appspot.com',
    androidClientId: '58788357910-abim13e9nvaf4g4as3sqbodfqct6hrgb.apps.googleusercontent.com',
    iosClientId: '58788357910-06af7pvn85hkt8lpa0699bcau39afohe.apps.googleusercontent.com',
    iosBundleId: 'com.example.mine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKx94sJHtx6yL3zoy8F2pBtylzwlTMRaw',
    appId: '1:58788357910:ios:3e7add3fbcab628fa3d237',
    messagingSenderId: '58788357910',
    projectId: 'kayou-47924',
    storageBucket: 'kayou-47924.appspot.com',
    androidClientId: '58788357910-abim13e9nvaf4g4as3sqbodfqct6hrgb.apps.googleusercontent.com',
    iosClientId: '58788357910-06af7pvn85hkt8lpa0699bcau39afohe.apps.googleusercontent.com',
    iosBundleId: 'com.example.mine',
  );
}
